build(craco): use craco-swc plugin to speed up build time
ReAGEnT-WiSe2021-22/frontend-v2 pull request #15
Opened 2021-12-01 10:11 UTC by LouisAndrew

2021-12-01 10:14 UTC, sunanmau5 approved these changes

2021-12-01 10:15 UTC, sunanmau5 requested changes
Tests failing

2021-12-01 10:24 UTC, LouisAndrew commented
> Tests failing

fixd

2021-12-03 18:59 UTC, sunanmau5 approved these changes

2021-12-04 09:46 UTC, merged