feat(setup): create artificial tweet component
ReAGEnT-WiSe2021-22/frontend-v2 pull request #21
Opened 2021-12-07 20:20 UTC by sunanmau5

- create artificial tweet component using direflow
- add generate tweet UI component
![image](https://user-images.githubusercontent.com/72509654/145100271-83f04b61-5124-4ca0-b35a-b2bb227a8475.png)

- add ability to copy generated tweet
![image](https://user-images.githubusercontent.com/72509654/145100305-39ba34e0-562b-4195-a49d-b03ba7495a75.png)

2021-12-07 20:46 UTC, NathanaelHermanto approved these changes

2021-12-07 20:48 UTC, LouisAndrew commented on packages/artificial-tweet/src/direflow-components/artificial-tweet/components/wrapper.tsx
> +  const generateTweet = useCallback(() => {
Why do we need usecallback here?

2021-12-08 09:13 UTC, LouisAndrew requested changes

2021-12-08 09:13 UTC, LouisAndrew commented on packages/artificial-tweet/src/direflow-components/artificial-tweet/components/wrapper.tsx
> +          <Typography sx={{ mr: 1 }}>{generatedTweet}</Typography>
Would be nice to have an indicator that this is the generated tweet

2021-12-08 09:13 UTC, LouisAndrew commented on packages/artificial-tweet/src/direflow-components/artificial-tweet/components/wrapper.tsx
> +        <Box sx={{ display: 'flex' }}>
Maybe add some padding?

2021-12-08 09:13 UTC, LouisAndrew commented on packages/artificial-tweet/src/direflow-components/artificial-tweet/components/wrapper.tsx
> +import { CopyToClipboard } from 'react-copy-to-clipboard';
Food for thought: do we really need the `CopyToClipboard` library? https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API? Whatever you choose it's fine

2021-12-08 20:51 UTC, LouisAndrew approved these changes
🍕🍕

2021-12-12 14:43 UTC, merged